version: '2'
services:
  moodle:
    image: k-tokiwa/moodle-nginx
    links:
      - moodle_db
    environment:
    # MOODLE_URL change. 
      MOODLE_URL: "https://0.0.0.0:8080"
      DB_PORT_3306_TCP_ADDR: moodle_db
      DB_ENV_MYSQL_USER: moodle
      DB_ENV_MYSQL_PASSWORD: moodle
      DB_ENV_MYSQL_DATABASE: moodle
    ports:
      - "8080:80"

  moodle_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    ports:
      - "3306:3306"
    volumes:
      - .data/moodledb:/var/lib/mysql
